name: Unzip Decode Base64 Data
description: Unzip Decode Base64 Data

inputs:
  zip-data:
    description: zip Data Base64
    type: string
  unzip-pass:
    description: unzip passwod
    type: string
  

runs:
  using: composite
  steps:
    - name: Base64 Decrypt
      shell: sh
      run: |
        # base64 input.zip | tr -d '\n' > input-encode.txt
        echo "${{inputs.zip-data}}" | base64 -d > ./input-base64-decode.zip
        if [ $? -ne 0 ]; then
            exit 101
        fi
        
        if [! -f ./input-base64-decode.zip ]; then
            ls -1 ./
            exit 102
        fi

        unzip -P "${{inputs.unzip-pass}}" -o ./input-base64-decode.zip

        if [ $? -ne 0 ]; then
            rm ./input-base64-decode.zip
            ls -1 ./
            exit 103
        fi
        rm ./input-base64-decode.zip
        ls -1 ./