name: Unzip Decrypt Base64 Data
description: Unzip Decrypt Base64 Data

inputs:
  encrypt-data:
    description: encrypt Data Base64
    type: string
  encrypt-pass:
    description: encrypt Key
    type: string
  encrypt-iter:
    description: encrypt IV
    type: string
  unzip-key:
    description: unzip key
    type: string
  unzip-exdir:
    description: unzip exdir

runs:
  using: composite
  steps:
    - name: Unzip Decrypt
      shell: sh
      run: |
        # openssl enc -aes-256-cfb -salt -iter 10000 -pass pass:"123456789" -in input.zip -A -a -out encrypted_file.txt
        # echo "encrypt data base64" | openssl enc -d -aes-256-cfb -iter 10000 -pass pass:"123456789" -a -out input-decrypted.zip
        echo "${{inputs.encrypt-data}}" | openssl enc -d -aes-256-cfb -iter ${{inputs.encrypt-iter}} -pass pass:${{ inputs.encrypt-pass }} -a -out input-base64-decrypted.zip 
        if [ $? -ne 0 ]; then
            exit 101
        fi
        unzip -P "${{inputs.unzip-key}}" -o input-base64-decrypted.zip -d ${{inputs.unzip-exdir||'./'}}
        if [ $? -ne 0 ]; then
            rm input-base64-decrypted.zip
            ls -1 ./
            ls -1 ${{inputs.unzip-exdir||'./'}}
            exit 102
        fi
        rm input-base64-decrypted.zip
        ls -1 ./
        ls -1 ${{inputs.unzip-exdir||'./'}}